---
#
# typical run:
#
# ansible-playbook -i env/<ENVIRONMENT> [-e spwa=True] MFRC522-trigger.yml
#
#

- name: Install MFRC522-trigger as systemd service
  hosts: volumio
  gather_facts: false

  vars:

    mfrc522:
      user: "volumio"
      group: "volumio"
      executable: "/home/volumio/devel/MFRC522-trigger/MFRC522-trigger.py"

  roles:

    - name: systemd
      systemd_service: "MFRC522-trigger"
      systemd_service_template: "MFRC522-trigger.service.j2"

    - name: systemd
      systemd_service: "speakerbonnet-workaround"
      systemd_service_template: "speakerbonnet-workaround.service.j2"
      when: spwa | default(False)
